mutation CompleteQuest($userId: Int!, $questId: String!, $title: String!, $description: String!, $xpReward: Int!, $category: String!, $difficulty: String!, $questType: String!, $target: Int!) {
    completeQuest(userId: $userId, questId: $questId, title: $title, description: $description, xpReward: $xpReward, category: $category, difficulty: $difficulty, questType: $questType, target: $target) {
        username
        level
        experience
        xpGained
        leveledUp
        xpForNextLevel
    }
}