type Query {
    me(token: String!): UserProfile
    getRandomQuests(count: Int): [Quest!]!
    getReplacementQuest(excludeTypes: [String!]!): Quest
    getCompletedQuests(userId: Int!): [Quest!]!
    getCompletedQuestsCount(userId: Int!): Int!
}

type Mutation {
    register(email: String!, password: String!, username: String!): AuthResponse
    login(email: String!, password: String!): AuthResponse
    completeQuest(userId: Int!, questId: String!, title: String!, description: String!, xpReward: Int!, category: String!, difficulty: String!, questType: String!, target: Int!): CompleteQuestResponse
    forgeQuest(userId: Int!, title: String!, questType: String!, target: Int!, targetLabel: String): Quest
}

type UserProfile {
    username: String!
    level: Int!
    experience: Int!
    xpForNextLevel: Int!
}

type AuthResponse {
    success: Boolean!
    message: String!
    token: String
}

type Quest {
    id: String!
    title: String!
    description: String!
    xpReward: Int!
    category: String!
    difficulty: String!
    questType: String!
    target: Int!
}

type CompleteQuestResponse {
    username: String!
    level: Int!
    experience: Int!
    xpGained: Int!
    leveledUp: Boolean!
    xpForNextLevel: Int!
}